baseURL       = "https://anthropoleo.github.io/coffee-shop/" # GitHub Pages URL
languageCode  = "en-us"
title         = "IMPULSO Café | Canelones, Uruguay"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Acerca nuestro"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Menu"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Contacto"
    url     = "contact"
    weight  = 4

# Define blog section
[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  blog = ["HTML", "RSS"]

# Site Params
[params]
  logo = "images/logo.png"
  logo_footer = "images/logo-footer.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "IMPULSO Café - Un lugar acogedor en Canelones para disfrutar de un buen café y más."
  author = "leandro falero (leo)"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/OOj8y6Y"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Nombre"
    placeholder_last_name         = "Apellido"
    placeholder_email             = "Correo Electrónico"
    placeholder_project_type      = "Tipo de consulta"
    placeholder_about_the_project = "Mensaje"
    send_message                  = "Enviar Mensaje"

    [[params.contactForm.projectType]]
      value = "cp"
      title  = "Cafécito"
 #   [[params.contactForm.projectType]]
 #     value = "bs"
 #     title  = "Bebidas y Snacks"   ESTO LO REMOVI POR AHORA PORQUE DEBERIA HABER UNA SOLA OPCION
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contacto"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "IMPULSO Café"
    tagline               = "Un lugar acogedor en Canelones para disfrutar de un buen café y más."
    primary_button        = "Cosas ricas"
    primary_button_url    = "portfolio"
    secondary_button      = "Contactanos"
    secondary_button_url  = "contact"

  [params.blog]
    enable = true
    title = "Blog"
    subtitle = "Nuestras últimas publicaciones"
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "NUESTRO RICO MENÚ"
    subtitle  = "Disfruta de cosas ricas entre amigos."
    view_project = "Ver menu"
    more_works = "MORE WORKS"
    scroll_down = "Hacia abajo"

    [[params.portfolio.link]]
      name = "Dulces"
      url  = "dulces"
    [[params.portfolio.link]]
      name = "Salados"
      url  = "salados"
    [[params.portfolio.link]]
      name = "Cafeteria"
      url  = "cafeteria"
    [[params.portfolio.link]]
      name = "Bebidas"
      url  = "bebidas"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Venite a tomar un café"
    primary_button      = "Mostrame el menu"
    primary_button_url  = "portfolio"  
    secondary_button    = "Manda un mensaje" 
    secondary_button_url = "contact"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Treinta y tres N 641, Canelones, Uruguay"
      phone   = "091 520 937"
      email   = "impulsocafecanelones@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Acerca nuestro"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Menu"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Contacto"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Redes Sociales"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/impulso_cafe/"
      # Footer Service
      [params.footer.service]
        title       = "Ofrecemos:"
        description = "cafecito rico<br>comidas<br>atmosfera relajante"
      [params.footer.back_to_top]
        description = "Llevame al principio"

[permalinks]
  blog = "/blog/:filename/"
